const users = [
  {
    _id: "1",
    username: "kingofsoul",
    email: "jamesbrown@selfproclaimed.com",
    password: "1234567899",
    minions: [],
    friends: [],
  },
  {
    _id: "2",
    username: "kingofpop",
    email: "mjackson@deadandcancelled.com",
    password: "1234567899",
    minions: [],
    friends: [],
  },
  {
    _id: "3",
    username: "kingofrock",
    email: "dethklok@fragglerock.com",
    password: "1234567899",
    minions: [],
    friends: [],
  },
  {
    _id: "4",
    username: "ludwigcangethova",
    email: "notjayz@htotheizzo.com",
    password: "1234567899",
    minions: [],
    friends: [],
  },
  {
    _id: "5",
    username: "nomorekings",
    email: "che@revolutionarybutequal.com",
    password: "1234567899",
    minions: [],
    friends: [],
  },
  {
    _id: "6",
    username: "kingofqueens",
    email: "whatdidi@justsay.com",
    password: "1234567899",
    minions: [],
    friends: [],
  },
  {
    _id: "7",
    username: "queenofengland",
    email: "charles@looksgreatinadress.com",
    password: "1234567899",
    minions: [],
    friends: [],
  },
  {
    _id: "8",
    username: "fuckthepatriarchy",
    email: "greta@shouldbethunderberg.com",
    password: "1234567899",
    minions: [],
    friends: [],
  },
  {
    _id: "9",
    username: "cursingbrokemyide",
    email: "fuck@mademycopilotquit.com",
    password: "1234567899",
    minions: [],
    friends: [],
  },
  {
    _id: "10",
    username: "nowiworkalone",
    email: "liketheydid@indaysofyore.com",
    password: "1234567899",
    minions: [],
    friends: [],
  },
];
